repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.3  # Check for the latest version at https://github.com/astral-sh/ruff-pre-commit
    hooks:
      - id: ruff
        args: ["--fix"]  # auto-fixes lint issues AND import order
      - id: ruff-format  # auto-formats code like black
