services:

  # MinIO Object Storage
  # For storing ML models
  minio:
    image: quay.io/minio/minio:latest
    container_name: rent-price-minio
    command: server /data --console-address ':9001'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./minio:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped

  # MLflow Tracking Server
  # For tracking experiments and storing models
  mlflow:
    container_name: rent-price-mlflow
    image: ghcr.io/mlflow/mlflow:v3.1.1
    depends_on:
      - minio
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow:/mlflow
    environment:
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
    command: >
      mlflow server
      --backend-store-uri sqlite:////mlflow/mlflow.db
      --default-artifact-root s3://mlflow-artifacts/
      --host 0.0.0.0
      --port 5000
    restart: unless-stopped

  # ML Microservice UI
  # A Streamlit UI for the ML microservice
  streamlit:
   build:
     context: ./src/streamlit_app
   image: rent-price-streamlit:latest
   container_name: streamlit
   ports:
     - '8501:8501'
   environment:
     - MLFLOW_TRACKING_URI=http://mlflow:5000
     - MLFLOW_TRACKING_URI=http://mlflow:5000
     - AWS_ACCESS_KEY_ID=minioadmin
     - AWS_SECRET_ACCESS_KEY=minioadmin
     - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
   depends_on:
     - mlflow