FROM python:3.12-slim

WORKDIR /code/user_interface/

COPY pyproject.toml /code/user_interface/
COPY src/ /code/user_interface/src/

# Required for XGBoost
RUN apt-get update && apt-get install -y libgomp1

RUN python -m pip install .

ENTRYPOINT [ "python", "-m", "streamlit", "run", "src/app.py"]